# Generated by Django 3.2.8 on 2022-02-02 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerSide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('customer_mobile', models.CharField(max_length=13, unique=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_city', models.CharField(max_length=30)),
                ('customer_state', models.CharField(max_length=30)),
                ('customer_pincode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('product_desc', models.TextField()),
                ('product_mrp', models.FloatField()),
                ('product_salePrice', models.FloatField()),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('product_cat', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AddField(
            model_name='account',
            name='userid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeid', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=20)),
                ('store_city', models.CharField(max_length=30)),
                ('store_state', models.CharField(max_length=30)),
                ('store_pincode', models.CharField(max_length=30)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerSide.account')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('customer_mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerSide.customer')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellerSide.product')),
            ],
        ),
    ]
